# This is a basic workflow to help you get started with Actions

name: CI TLC True Love club

# Controls when the workflow will runTrue love club, it's a social service of Shalom Center Ministry called to be holistic on its function. 
on:
  # Triggers the workflow on push or pull request events but only for the gh-pages branch
  push:https:// truelocec.com
    branches: [ gh-pages ] tlc-true love clup app 
  pull_request:
    branches: [ gh-pages ]https://trruelovec.com

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: True love club  project

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: t.L. C True love club
  # This workflow contains a single job called "build"
  build: tlc-app-tlc-contant- tlc-about-tlc-home- tlc-app -tlc-coffee-tlc-tlc-liveStreaming-tlc-contact-tlc-leadeship  
    # The type of runner that the job will run on trueloveclub
    runs-on: ubuntu-latest https://truelovec.com

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
